version: 2.1

jobs:
  build:
    environment:
      NODE_ENV: 'test'
      MONGOMS_DEBUG : 1
      JWT_SECRET : 'f20971cd002aee78f425219fcf1e2769e84efcff55a4f57187e66de1557068a6b8fe7b0ef774d8b9ab3a5acdc56fea2a4b16adfa334cfe327dba81ed09410023'
      
    working_directory: ~/notes-api
    docker:
      - image: cimg/node:19.7.0
      - image: mongo:4.1.6-xenial
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
      
      - run:
          name: Install project dependencies

          command: npm install --verbose
      
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules
      
      - run:
          echo "MONGO_URI = 'mongodb://localhost:27017/'" > ./.env
      - run:
          npx eslint

      - run:
          name: Run tests

          command: npm test -- --runInBand

workflows:
  version: 2.1

  run_build:
    jobs:
      - build




    